export const informatonPruebas = [
  {
    name: "Pruebas",
    lastName: "Perez",
    identificationDocument: "40123456",
    gender: "Masculino",
    dateOfBirth: "22/01/1981",
    nationality: "Venezuela",
    countryOfBirth: "Venezuela",
    stateOfBirth: "Caracas",
    mainEmail: "marianella.gonzalezgrau@telefonica.com",
    alternateEmail: "marianella.gonzalezgrau@telefonica.com",
    Facebook: "",
    Twitter: "@marianellagonzalez@telefonica.com",
    phoneMajor: "",
    phoneSecondary: "414-3366565",
    phoneOffice: "2342566565",
    phoneRoom: "2122566565",
    fiscalAddress: "Av Principal Nuevo Piso 3 Apt 39 Urb Bello Monte 1050 Bolivariano libertador Cracas Distrito Capital",
    OfficeAddress: "Av Principal Nuevo Piso 3 Apt 39 Urb Bello Monte 1050 Bolivariano libertador Cracas Distrito Capital",
    phone: "414-3366565",
    edit: true
  },
  {
    name: "Alfredo A.",
    lastName: "Caqizalez Casique",
    identificationDocument: "25.219.663",
    gender: "",
    dateOfBirth: "22/01/1995",
    nationality: "Venezuela",
    countryOfBirth: "Venezuela",
    stateOfBirth: "",
    mainEmail: "",
    alternateEmail: "",
    Facebook: "",
    Twitter: "",
    phoneMajor: "414-9911815",
    phoneSecondary: "",
    phoneOffice: "",
    phoneRoom: "",
    fiscalAddress: "",
    OfficeAddress: "",
    phone: "0424-1767607",
    edit: false
  }
]
